OES-33 delete users functionality in openam
tabordasolutions/nics-tools pull request #1
Opened 2017-02-23 17:39 UTC by sneha-nagole

# Summary
Expose new method to delete users by uid from OpenAm

# what's new
New method to delete users by uid from OpenAm

# what is changed

2017-02-24 15:56 UTC, DreamWver approved these changes

2017-02-24 16:39 UTC, comeara requested changes
Good job working in a tough code base.

Functionally, I think this is fine and follows the patterns established in the code.

Mid-to-long term, I want to get away from Util classes like this. We want to get to the place where we are not adding methods to classes with 1000+ lines of code.

2017-02-24 16:39 UTC, comeara commented on openam-tools/src/main/java/edu/mit/ll/soa/sso/util/OpenAmBaseUtil.java
> +                System.out.println("idRepo is null!");
Please change System.out.println calls to debug log entries or remove.

2017-02-24 16:39 UTC, comeara commented on openam-tools/src/main/java/edu/mit/ll/soa/sso/util/OpenAmBaseUtil.java
> +    private Set findIdentityByUID(String uid) throws Exception {
You can use your discretion as to whether you want to incorporate this or not but here is a more succinct and type-safe implementation.

```
	private Set findIdentityByUID(String uid) throws Exception {
		Map<String, Set<String>> criteria = Collections.singletonMap("uid", Collections.singleton(uid));
		IdSearchControl searchControl = new IdSearchControl();
		searchControl.setSearchModifiers(IdSearchOpModifier.AND, criteria);
		return idRepo.searchIdentities(IdType.USER, "*", searchControl).getSearchResults();
	}
```

2017-02-24 16:39 UTC, comeara commented on sso-tools/src/main/java/edu/mit/ll/nics/sso/util/SSOUtil.java
> +        return "{\"status\":\"" + ((status) ? "success" : "fail") + "\",\"message\":\"" + message + "\"}";
I see how you were following an existing pattern here and I appreciate that. Returning a string that can be parsed into JSON is not the kind of design we want to propagate in the project.

2017-02-25 17:40 UTC, comeara approved these changes
👍

2017-02-28 17:01 UTC, merged